import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import model.Location;
import model.WeatherData;

public class Main {
    public static void main(String[] args) throws JsonProcessingException {
        String jsonResponse = """
{
  "location": {
    "name": "London",
    "region": "City of London, Greater London",
    "country": "United Kingdom",
    "lat": 51.52,
    "lon": -0.11,
    "tz_id": "Europe/London",
    "localtime_epoch": 1713872668,
    "localtime": "2024-04-23 12:44"
  },
  "current": {
    "last_updated_epoch": 1713871800,
    "last_updated": "2024-04-23 12:30",
    "temp_c": 9.0,
    "temp_f": 48.2,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 11.9,
    "wind_kph": 19.1,
    "wind_degree": 10,
    "wind_dir": "N",
    "pressure_mb": 1022.0,
    "pressure_in": 30.18,
    "precip_mm": 0.02,
    "precip_in": 0.0,
    "humidity": 71,
    "cloud": 75,
    "feelslike_c": 7.1,
    "feelslike_f": 44.7,
    "vis_km": 10.0,
    "vis_miles": 6.0,
    "uv": 2.0,
    "gust_mph": 16.3,
    "gust_kph": 26.3
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2024-04-23",
        "date_epoch": 1713830400,
        "day": {
          "maxtemp_c": 10.5,
          "maxtemp_f": 50.9,
          "mintemp_c": 5.0,
          "mintemp_f": 41.1,
          "avgtemp_c": 7.0,
          "avgtemp_f": 44.7,
          "maxwind_mph": 11.4,
          "maxwind_kph": 18.4,
          "totalprecip_mm": 1.24,
          "totalprecip_in": 0.05,
          "totalsnow_cm": 0.0,
          "avgvis_km": 9.3,
          "avgvis_miles": 5.0,
          "avghumidity": 80,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 88,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain nearby",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 2.0
        },
        "astro": {
          "sunrise": "05:47 AM",
          "sunset": "08:11 PM",
          "moonrise": "07:59 PM",
          "moonset": "05:30 AM",
          "moon_phase": "Full Moon",
          "moon_illumination": 99,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1713826800,
            "time": "2024-04-23 00:00",
            "temp_c": 6.0,
            "temp_f": 42.8,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 0.05,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 5.5,
            "feelslike_f": 41.8,
            "windchill_c": 5.5,
            "windchill_f": 41.8,
            "heatindex_c": 6.0,
            "heatindex_f": 42.8,
            "dewpoint_c": 3.7,
            "dewpoint_f": 38.6,
            "will_it_rain": 1,
            "chance_of_rain": 79,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.8,
            "gust_kph": 6.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1713830400,
            "time": "2024-04-23 01:00",
            "temp_c": 5.9,
            "temp_f": 42.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 47,
            "wind_dir": "NE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.26,
            "precip_mm": 0.02,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 5.9,
            "feelslike_f": 42.6,
            "windchill_c": 5.9,
            "windchill_f": 42.6,
            "heatindex_c": 5.9,
            "heatindex_f": 42.6,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.4,
            "will_it_rain": 1,
            "chance_of_rain": 72,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1713834000,
            "time": "2024-04-23 02:00",
            "temp_c": 5.9,
            "temp_f": 42.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 345,
            "wind_dir": "NNW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.25,
            "precip_mm": 0.03,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 5.9,
            "feelslike_f": 42.6,
            "windchill_c": 5.9,
            "windchill_f": 42.6,
            "heatindex_c": 5.9,
            "heatindex_f": 42.6,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 1,
            "chance_of_rain": 88,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.3,
            "gust_kph": 2.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1713837600,
            "time": "2024-04-23 03:00",
            "temp_c": 5.9,
            "temp_f": 42.6,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.24,
            "precip_mm": 0.04,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 86,
            "cloud": 100,
            "feelslike_c": 5.9,
            "feelslike_f": 42.6,
            "windchill_c": 5.9,
            "windchill_f": 42.6,
            "heatindex_c": 5.9,
            "heatindex_f": 42.6,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 68,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1713841200,
            "time": "2024-04-23 04:00",
            "temp_c": 5.8,
            "temp_f": 42.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 315,
            "wind_dir": "NW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 0.03,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 5.8,
            "feelslike_f": 42.5,
            "windchill_c": 5.8,
            "windchill_f": 42.5,
            "heatindex_c": 5.8,
            "heatindex_f": 42.5,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 1,
            "chance_of_rain": 79,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.6,
            "gust_kph": 4.1,
            "uv": 1.0
          },
          {
            "time_epoch": 1713844800,
            "time": "2024-04-23 05:00",
            "temp_c": 5.8,
            "temp_f": 42.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 302,
            "wind_dir": "WNW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 0.03,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 86,
            "cloud": 100,
            "feelslike_c": 5.4,
            "feelslike_f": 41.7,
            "windchill_c": 5.4,
            "windchill_f": 41.7,
            "heatindex_c": 5.8,
            "heatindex_f": 42.4,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 1,
            "chance_of_rain": 89,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.4,
            "gust_kph": 5.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1713848400,
            "time": "2024-04-23 06:00",
            "temp_c": 5.8,
            "temp_f": 42.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 296,
            "wind_dir": "WNW",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 87,
            "cloud": 100,
            "feelslike_c": 5.2,
            "feelslike_f": 41.4,
            "windchill_c": 5.2,
            "windchill_f": 41.4,
            "heatindex_c": 5.8,
            "heatindex_f": 42.4,
            "dewpoint_c": 3.7,
            "dewpoint_f": 38.7,
            "will_it_rain": 0,
            "chance_of_rain": 68,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.7,
            "gust_kph": 5.9,
            "uv": 2.0
          },
          {
            "time_epoch": 1713852000,
            "time": "2024-04-23 07:00",
            "temp_c": 5.8,
            "temp_f": 42.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 288,
            "wind_dir": "WNW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.22,
            "precip_mm": 0.03,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 88,
            "cloud": 100,
            "feelslike_c": 5.0,
            "feelslike_f": 41.0,
            "windchill_c": 5.0,
            "windchill_f": 41.0,
            "heatindex_c": 5.8,
            "heatindex_f": 42.5,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39.1,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.3,
            "gust_kph": 6.9,
            "uv": 2.0
          },
          {
            "time_epoch": 1713855600,
            "time": "2024-04-23 08:00",
            "temp_c": 5.9,
            "temp_f": 42.6,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 294,
            "wind_dir": "WNW",
            "pressure_mb": 1024.0,
            "pressure_in": 30.23,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 90,
            "cloud": 100,
            "feelslike_c": 4.4,
            "feelslike_f": 39.9,
            "windchill_c": 4.4,
            "windchill_f": 39.9,
            "heatindex_c": 5.9,
            "heatindex_f": 42.6,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.8,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.2,
            "gust_kph": 9.9,
            "uv": 2.0
          },
          {
            "time_epoch": 1713859200,
            "time": "2024-04-23 09:00",
            "temp_c": 6.2,
            "temp_f": 43.1,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 6.0,
            "wind_kph": 9.7,
            "wind_degree": 322,
            "wind_dir": "NW",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.16,
            "precip_in": 0.01,
            "snow_cm": 0.0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 4.1,
            "feelslike_f": 39.4,
            "windchill_c": 4.1,
            "windchill_f": 39.4,
            "heatindex_c": 6.2,
            "heatindex_f": 43.1,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 2.0
          },
          {
            "time_epoch": 1713862800,
            "time": "2024-04-23 10:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 337,
            "wind_dir": "NNW",
            "pressure_mb": 1023.0,
            "pressure_in": 30.22,
            "precip_mm": 0.08,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 89,
            "cloud": 100,
            "feelslike_c": 3.9,
            "feelslike_f": 38.9,
            "windchill_c": 3.9,
            "windchill_f": 38.9,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": 4.6,
            "dewpoint_f": 40.3,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.4,
            "uv": 2.0
          },
          {
            "time_epoch": 1713866400,
            "time": "2024-04-23 11:00",
            "temp_c": 6.7,
            "temp_f": 44.0,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1023.0,
            "pressure_in": 30.21,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 86,
            "cloud": 100,
            "feelslike_c": 4.4,
            "feelslike_f": 40.0,
            "windchill_c": 4.4,
            "windchill_f": 40.0,
            "heatindex_c": 6.7,
            "heatindex_f": 44.0,
            "dewpoint_c": 4.6,
            "dewpoint_f": 40.2,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713870000,
            "time": "2024-04-23 12:00",
            "temp_c": 9.0,
            "temp_f": 48.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 10,
            "wind_dir": "N",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.02,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 71,
            "cloud": 75,
            "feelslike_c": 5.6,
            "feelslike_f": 42.0,
            "windchill_c": 5.6,
            "windchill_f": 42.0,
            "heatindex_c": 7.8,
            "heatindex_f": 46.0,
            "dewpoint_c": 4.4,
            "dewpoint_f": 39.9,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 16.3,
            "gust_kph": 26.3,
            "uv": 2.0
          },
          {
            "time_epoch": 1713873600,
            "time": "2024-04-23 13:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.13,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 68,
            "cloud": 100,
            "feelslike_c": 7.7,
            "feelslike_f": 45.8,
            "windchill_c": 7.7,
            "windchill_f": 45.8,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 4.2,
            "dewpoint_f": 39.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.6,
            "gust_kph": 17.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713877200,
            "time": "2024-04-23 14:00",
            "temp_c": 9.9,
            "temp_f": 49.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 329,
            "wind_dir": "NNW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.12,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 65,
            "cloud": 100,
            "feelslike_c": 7.8,
            "feelslike_f": 46.0,
            "windchill_c": 7.8,
            "windchill_f": 46.0,
            "heatindex_c": 9.9,
            "heatindex_f": 49.9,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.5,
            "gust_kph": 20.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713880800,
            "time": "2024-04-23 15:00",
            "temp_c": 9.4,
            "temp_f": 48.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 354,
            "wind_dir": "N",
            "pressure_mb": 1021.0,
            "pressure_in": 30.15,
            "precip_mm": 0.1,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": 7.0,
            "feelslike_f": 44.5,
            "windchill_c": 7.0,
            "windchill_f": 44.5,
            "heatindex_c": 9.4,
            "heatindex_f": 48.9,
            "dewpoint_c": 4.7,
            "dewpoint_f": 40.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713884400,
            "time": "2024-04-23 16:00",
            "temp_c": 8.5,
            "temp_f": 47.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 9,
            "wind_dir": "N",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.04,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 62,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 8.5,
            "heatindex_f": 47.2,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39.0,
            "will_it_rain": 0,
            "chance_of_rain": 68,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.8,
            "gust_kph": 15.7,
            "uv": 2.0
          },
          {
            "time_epoch": 1713888000,
            "time": "2024-04-23 17:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 13,
            "wind_dir": "NNE",
            "pressure_mb": 1021.0,
            "pressure_in": 30.15,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 61,
            "cloud": 86,
            "feelslike_c": 7.3,
            "feelslike_f": 45.1,
            "windchill_c": 7.3,
            "windchill_f": 45.1,
            "heatindex_c": 9.8,
            "heatindex_f": 49.6,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.9,
            "gust_kph": 22.4,
            "uv": 2.0
          },
          {
            "time_epoch": 1713891600,
            "time": "2024-04-23 18:00",
            "temp_c": 8.1,
            "temp_f": 46.6,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 20,
            "wind_dir": "NNE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 65,
            "cloud": 31,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8.1,
            "heatindex_f": 46.6,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.2,
            "gust_kph": 19.7,
            "uv": 3.0
          },
          {
            "time_epoch": 1713895200,
            "time": "2024-04-23 19:00",
            "temp_c": 7.0,
            "temp_f": 44.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 17,
            "wind_dir": "NNE",
            "pressure_mb": 1022.0,
            "pressure_in": 30.17,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 66,
            "cloud": 18,
            "feelslike_c": 4.7,
            "feelslike_f": 40.4,
            "windchill_c": 4.7,
            "windchill_f": 40.4,
            "heatindex_c": 7.0,
            "heatindex_f": 44.5,
            "dewpoint_c": 1.0,
            "dewpoint_f": 33.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.1,
            "gust_kph": 17.8,
            "uv": 3.0
          },
          {
            "time_epoch": 1713898800,
            "time": "2024-04-23 20:00",
            "temp_c": 5.9,
            "temp_f": 42.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 352,
            "wind_dir": "N",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 69,
            "cloud": 5,
            "feelslike_c": 4.1,
            "feelslike_f": 39.3,
            "windchill_c": 4.1,
            "windchill_f": 39.3,
            "heatindex_c": 5.9,
            "heatindex_f": 42.7,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.7,
            "gust_kph": 14.0,
            "uv": 3.0
          },
          {
            "time_epoch": 1713902400,
            "time": "2024-04-23 21:00",
            "temp_c": 5.4,
            "temp_f": 41.8,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 321,
            "wind_dir": "NW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 9,
            "feelslike_c": 3.7,
            "feelslike_f": 38.6,
            "windchill_c": 3.7,
            "windchill_f": 38.6,
            "heatindex_c": 5.4,
            "heatindex_f": 41.8,
            "dewpoint_c": 1.1,
            "dewpoint_f": 33.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.2,
            "gust_kph": 13.2,
            "uv": 1.0
          },
          {
            "time_epoch": 1713906000,
            "time": "2024-04-23 22:00",
            "temp_c": 5.0,
            "temp_f": 41.1,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 310,
            "wind_dir": "NW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.16,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 77,
            "cloud": 36,
            "feelslike_c": 3.0,
            "feelslike_f": 37.4,
            "windchill_c": 3.0,
            "windchill_f": 37.4,
            "heatindex_c": 5.0,
            "heatindex_f": 41.1,
            "dewpoint_c": 1.4,
            "dewpoint_f": 34.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.1,
            "gust_kph": 14.6,
            "uv": 1.0
          },
          {
            "time_epoch": 1713909600,
            "time": "2024-04-23 23:00",
            "temp_c": 4.8,
            "temp_f": 40.6,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 316,
            "wind_dir": "NW",
            "pressure_mb": 1021.0,
            "pressure_in": 30.14,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 79,
            "cloud": 75,
            "feelslike_c": 2.5,
            "feelslike_f": 36.6,
            "windchill_c": 2.5,
            "windchill_f": 36.6,
            "heatindex_c": 4.8,
            "heatindex_f": 40.6,
            "dewpoint_c": 1.4,
            "dewpoint_f": 34.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.4,
            "uv": 1.0
          }
        ]
      },
      {
        "date": "2024-04-24",
        "date_epoch": 1713916800,
        "day": {
          "maxtemp_c": 9.8,
          "maxtemp_f": 49.7,
          "mintemp_c": 5.1,
          "mintemp_f": 41.3,
          "avgtemp_c": 7.1,
          "avgtemp_f": 44.7,
          "maxwind_mph": 11.6,
          "maxwind_kph": 18.7,
          "totalprecip_mm": 0.03,
          "totalprecip_in": 0.0,
          "totalsnow_cm": 0.0,
          "avgvis_km": 10.0,
          "avgvis_miles": 6.0,
          "avghumidity": 61,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 4.0
        },
        "astro": {
          "sunrise": "05:45 AM",
          "sunset": "08:13 PM",
          "moonrise": "09:15 PM",
          "moonset": "05:42 AM",
          "moon_phase": "Full Moon",
          "moon_illumination": 100,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1713913200,
            "time": "2024-04-24 00:00",
            "temp_c": 5.4,
            "temp_f": 41.8,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 321,
            "wind_dir": "NW",
            "pressure_mb": 1020.0,
            "pressure_in": 30.13,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 75,
            "cloud": 89,
            "feelslike_c": 3.1,
            "feelslike_f": 37.5,
            "windchill_c": 3.1,
            "windchill_f": 37.5,
            "heatindex_c": 5.4,
            "heatindex_f": 41.8,
            "dewpoint_c": 1.4,
            "dewpoint_f": 34.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1713916800,
            "time": "2024-04-24 01:00",
            "temp_c": 5.8,
            "temp_f": 42.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 328,
            "wind_dir": "NNW",
            "pressure_mb": 1020.0,
            "pressure_in": 30.12,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 83,
            "feelslike_c": 3.4,
            "feelslike_f": 38.1,
            "windchill_c": 3.4,
            "windchill_f": 38.1,
            "heatindex_c": 5.8,
            "heatindex_f": 42.4,
            "dewpoint_c": 1.4,
            "dewpoint_f": 34.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1713920400,
            "time": "2024-04-24 02:00",
            "temp_c": 5.7,
            "temp_f": 42.3,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 333,
            "wind_dir": "NNW",
            "pressure_mb": 1020.0,
            "pressure_in": 30.11,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 71,
            "feelslike_c": 3.0,
            "feelslike_f": 37.5,
            "windchill_c": 3.0,
            "windchill_f": 37.5,
            "heatindex_c": 5.7,
            "heatindex_f": 42.3,
            "dewpoint_c": 1.3,
            "dewpoint_f": 34.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.1,
            "gust_kph": 17.9,
            "uv": 1.0
          },
          {
            "time_epoch": 1713924000,
            "time": "2024-04-24 03:00",
            "temp_c": 5.6,
            "temp_f": 42.2,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 8.1,
            "wind_kph": 13.0,
            "wind_degree": 328,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.09,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": 2.9,
            "feelslike_f": 37.2,
            "windchill_c": 2.9,
            "windchill_f": 37.2,
            "heatindex_c": 5.6,
            "heatindex_f": 42.2,
            "dewpoint_c": 1.1,
            "dewpoint_f": 34.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.5,
            "gust_kph": 18.5,
            "uv": 1.0
          },
          {
            "time_epoch": 1713927600,
            "time": "2024-04-24 04:00",
            "temp_c": 5.5,
            "temp_f": 41.9,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 333,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 71,
            "cloud": 100,
            "feelslike_c": 2.5,
            "feelslike_f": 36.6,
            "windchill_c": 2.5,
            "windchill_f": 36.6,
            "heatindex_c": 5.5,
            "heatindex_f": 41.9,
            "dewpoint_c": 0.7,
            "dewpoint_f": 33.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.4,
            "gust_kph": 20.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1713931200,
            "time": "2024-04-24 05:00",
            "temp_c": 5.1,
            "temp_f": 41.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 337,
            "wind_dir": "NNW",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 71,
            "cloud": 100,
            "feelslike_c": 2.0,
            "feelslike_f": 35.7,
            "windchill_c": 2.0,
            "windchill_f": 35.7,
            "heatindex_c": 5.1,
            "heatindex_f": 41.1,
            "dewpoint_c": 0.3,
            "dewpoint_f": 32.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.0,
            "gust_kph": 19.3,
            "uv": 1.0
          },
          {
            "time_epoch": 1713934800,
            "time": "2024-04-24 06:00",
            "temp_c": 5.1,
            "temp_f": 41.2,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 341,
            "wind_dir": "NNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 68,
            "cloud": 85,
            "feelslike_c": 2.1,
            "feelslike_f": 35.8,
            "windchill_c": 2.1,
            "windchill_f": 35.8,
            "heatindex_c": 5.1,
            "heatindex_f": 41.3,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 2.0
          },
          {
            "time_epoch": 1713938400,
            "time": "2024-04-24 07:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 342,
            "wind_dir": "NNW",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 67,
            "cloud": 14,
            "feelslike_c": 2.3,
            "feelslike_f": 36.1,
            "windchill_c": 2.3,
            "windchill_f": 36.1,
            "heatindex_c": 5.3,
            "heatindex_f": 41.5,
            "dewpoint_c": -0.4,
            "dewpoint_f": 31.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.2,
            "gust_kph": 18.1,
            "uv": 3.0
          },
          {
            "time_epoch": 1713942000,
            "time": "2024-04-24 08:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.0,
            "wind_kph": 17.6,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.07,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 57,
            "cloud": 44,
            "feelslike_c": 3.3,
            "feelslike_f": 37.9,
            "windchill_c": 3.3,
            "windchill_f": 37.9,
            "heatindex_c": 6.5,
            "heatindex_f": 43.8,
            "dewpoint_c": -1.5,
            "dewpoint_f": 29.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.8,
            "gust_kph": 20.7,
            "uv": 3.0
          },
          {
            "time_epoch": 1713945600,
            "time": "2024-04-24 09:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1018.0,
            "pressure_in": 30.05,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 51,
            "cloud": 88,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": -1.9,
            "dewpoint_f": 28.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.4,
            "gust_kph": 21.5,
            "uv": 2.0
          },
          {
            "time_epoch": 1713949200,
            "time": "2024-04-24 10:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 351,
            "wind_dir": "N",
            "pressure_mb": 1017.0,
            "pressure_in": 30.04,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 47,
            "cloud": 77,
            "feelslike_c": 5.8,
            "feelslike_f": 42.5,
            "windchill_c": 5.8,
            "windchill_f": 42.5,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": -2.1,
            "dewpoint_f": 28.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713952800,
            "time": "2024-04-24 11:00",
            "temp_c": 9.5,
            "temp_f": 49.0,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 355,
            "wind_dir": "N",
            "pressure_mb": 1017.0,
            "pressure_in": 30.02,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 44,
            "cloud": 53,
            "feelslike_c": 6.9,
            "feelslike_f": 44.4,
            "windchill_c": 6.9,
            "windchill_f": 44.4,
            "heatindex_c": 9.5,
            "heatindex_f": 49.0,
            "dewpoint_c": -2.1,
            "dewpoint_f": 28.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 3.0
          },
          {
            "time_epoch": 1713956400,
            "time": "2024-04-24 12:00",
            "temp_c": 9.7,
            "temp_f": 49.4,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 1,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 45,
            "cloud": 63,
            "feelslike_c": 7.1,
            "feelslike_f": 44.8,
            "windchill_c": 7.1,
            "windchill_f": 44.8,
            "heatindex_c": 9.7,
            "heatindex_f": 49.4,
            "dewpoint_c": -1.6,
            "dewpoint_f": 29.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.4,
            "gust_kph": 21.5,
            "uv": 2.0
          },
          {
            "time_epoch": 1713960000,
            "time": "2024-04-24 13:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.4,
            "wind_kph": 18.4,
            "wind_degree": 3,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 30.01,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 48,
            "cloud": 77,
            "feelslike_c": 6.6,
            "feelslike_f": 43.9,
            "windchill_c": 6.6,
            "windchill_f": 43.9,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 13.1,
            "gust_kph": 21.1,
            "uv": 2.0
          },
          {
            "time_epoch": 1713963600,
            "time": "2024-04-24 14:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 355,
            "wind_dir": "N",
            "pressure_mb": 1016.0,
            "pressure_in": 30.0,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 48,
            "cloud": 91,
            "feelslike_c": 6.8,
            "feelslike_f": 44.2,
            "windchill_c": 6.8,
            "windchill_f": 44.2,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 12.1,
            "gust_kph": 19.5,
            "uv": 2.0
          },
          {
            "time_epoch": 1713967200,
            "time": "2024-04-24 15:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 351,
            "wind_dir": "N",
            "pressure_mb": 1015.0,
            "pressure_in": 29.98,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 48,
            "cloud": 88,
            "feelslike_c": 6.9,
            "feelslike_f": 44.5,
            "windchill_c": 6.9,
            "windchill_f": 44.5,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.1,
            "gust_kph": 17.8,
            "uv": 2.0
          },
          {
            "time_epoch": 1713970800,
            "time": "2024-04-24 16:00",
            "temp_c": 8.9,
            "temp_f": 48.0,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 352,
            "wind_dir": "N",
            "pressure_mb": 1015.0,
            "pressure_in": 29.97,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 50,
            "cloud": 93,
            "feelslike_c": 6.5,
            "feelslike_f": 43.7,
            "windchill_c": 6.5,
            "windchill_f": 43.7,
            "heatindex_c": 8.9,
            "heatindex_f": 48.0,
            "dewpoint_c": -0.9,
            "dewpoint_f": 30.4,
            "will_it_rain": 1,
            "chance_of_rain": 79,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.0,
            "gust_kph": 17.7,
            "uv": 2.0
          },
          {
            "time_epoch": 1713974400,
            "time": "2024-04-24 17:00",
            "temp_c": 8.3,
            "temp_f": 47.0,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.7,
            "wind_kph": 14.0,
            "wind_degree": 347,
            "wind_dir": "NNW",
            "pressure_mb": 1015.0,
            "pressure_in": 29.96,
            "precip_mm": 0.02,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 54,
            "cloud": 69,
            "feelslike_c": 6.0,
            "feelslike_f": 42.7,
            "windchill_c": 6.0,
            "windchill_f": 42.7,
            "heatindex_c": 8.3,
            "heatindex_f": 47.0,
            "dewpoint_c": -0.3,
            "dewpoint_f": 31.4,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.0,
            "gust_kph": 17.6,
            "uv": 2.0
          },
          {
            "time_epoch": 1713978000,
            "time": "2024-04-24 18:00",
            "temp_c": 8.0,
            "temp_f": 46.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 56,
            "cloud": 9,
            "feelslike_c": 5.8,
            "feelslike_f": 42.5,
            "windchill_c": 5.8,
            "windchill_f": 42.5,
            "heatindex_c": 8.0,
            "heatindex_f": 46.3,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 3.0
          },
          {
            "time_epoch": 1713981600,
            "time": "2024-04-24 19:00",
            "temp_c": 6.8,
            "temp_f": 44.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 63,
            "cloud": 4,
            "feelslike_c": 5.2,
            "feelslike_f": 41.4,
            "windchill_c": 5.2,
            "windchill_f": 41.4,
            "heatindex_c": 6.8,
            "heatindex_f": 44.3,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 3.0
          },
          {
            "time_epoch": 1713985200,
            "time": "2024-04-24 20:00",
            "temp_c": 5.8,
            "temp_f": 42.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 2,
            "wind_dir": "N",
            "pressure_mb": 1014.0,
            "pressure_in": 29.96,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 69,
            "cloud": 4,
            "feelslike_c": 5.0,
            "feelslike_f": 41.0,
            "windchill_c": 5.0,
            "windchill_f": 41.0,
            "heatindex_c": 5.8,
            "heatindex_f": 42.4,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.2,
            "gust_kph": 8.4,
            "uv": 3.0
          },
          {
            "time_epoch": 1713988800,
            "time": "2024-04-24 21:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 359,
            "wind_dir": "N",
            "pressure_mb": 1014.0,
            "pressure_in": 29.95,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 72,
            "cloud": 6,
            "feelslike_c": 4.9,
            "feelslike_f": 40.9,
            "windchill_c": 4.9,
            "windchill_f": 40.9,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 0.6,
            "dewpoint_f": 33.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.8,
            "gust_kph": 6.0,
            "uv": 1.0
          },
          {
            "time_epoch": 1713992400,
            "time": "2024-04-24 22:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1014.0,
            "pressure_in": 29.93,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 73,
            "cloud": 10,
            "feelslike_c": 4.9,
            "feelslike_f": 40.8,
            "windchill_c": 4.9,
            "windchill_f": 40.8,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": 0.5,
            "dewpoint_f": 33.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.5,
            "gust_kph": 2.4,
            "uv": 1.0
          },
          {
            "time_epoch": 1713996000,
            "time": "2024-04-24 23:00",
            "temp_c": 4.5,
            "temp_f": 40.2,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 205,
            "wind_dir": "SSW",
            "pressure_mb": 1013.0,
            "pressure_in": 29.92,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "snow_cm": 0.0,
            "humidity": 74,
            "cloud": 47,
            "feelslike_c": 4.6,
            "feelslike_f": 40.2,
            "windchill_c": 4.6,
            "windchill_f": 40.2,
            "heatindex_c": 4.6,
            "heatindex_f": 40.2,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.3,
            "gust_kph": 3.7,
            "uv": 1.0
          }
        ]
      }
    ]
  }
}
                """;
        ObjectMapper mapper = new ObjectMapper();
        mapper.findAndRegisterModules(); // Load date/time converters

        WeatherData parsedResponse = mapper.readerFor(WeatherData.class).readValue(jsonResponse);
        System.out.println(parsedResponse);
    }
}
